- name: install flydra package
  apt: name=python-flydra state=installed

- name: Ensure rosdep sources dir exists
  file: path=/etc/ros/rosdep/sources.list.d state=directory mode=0755 owner=root group=root

- name: Ensure strawlab rosdep URL is included into rosdep sources
  copy: src=40-strawlab-kinetic.list dest=/etc/ros/rosdep/sources.list.d/40-strawlab-kinetic.list owner=root group=root mode=0644

- name: Ensure flydra-kinetic-catkin.rosinstall is available
  copy: src=flydra-kinetic-catkin.rosinstall dest=/etc/ros/flydra-kinetic-catkin.rosinstall owner=root group=root mode=0644

- name: Ensure flydra-kinetic-rosbuild.rosinstall is available
  copy: src=flydra-kinetic-rosbuild.rosinstall dest=/etc/ros/flydra-kinetic-rosbuild.rosinstall owner=root group=root mode=0644

- name: install sudo command
  # This is required by `rosdep install`
  apt: name=sudo state=installed

- name: install wstool command
  # This is required for `wstool`
  apt: name=python-wstool state=installed

- name: install rosinstall command
  apt: name=python-rosinstall state=installed

- name: copy installer script
  copy: src=user-install-ros-kinetic-flydra.sh dest=/opt/ros/user-install-ros-kinetic-flydra.sh owner=root group=root mode=0755
