- name: get ROS apt signing key
  apt_key: id=B01FA116 url=http://packages.ros.org/ros.key state=present

- name: use ROS Ubuntu repository
  apt_repository: repo='deb http://packages.ros.org/ros/ubuntu {{ansible_lsb.codename}} main'

- name: use ROS Ubuntu source repository
  apt_repository: repo='deb-src http://packages.ros.org/ros/ubuntu {{ansible_lsb.codename}} main'

- name: install ROS kinetic packages
  apt: name=ros-kinetic-desktop-full state=installed
